url=https://test-edoc-gw.kakao.com/v1/envelopes/D42_2T
targetAuthorization=KakaoAK 46b050f23d6d7202d8ac97584978a7bc
authorization=KakaoAK 3f4785dfe31d5b9d0d82fe7b68f315ed
settleId=ff3266ca-d4b6-4091-b659-8dd4c783d77b
method=POST
ci=KvhdmEmq+EfoEPwXdj3WJpxmd5jNa7+0vo3pTBVhkHwVCuAah08T526woQKV19DcFjSXJwg8jpxiJyxTRzyb/g==

