url=https://private-edoc-gw.kakao.com/v1/envelopes/D42_1
targetAuthorization=KakaoAK 46b050f23d6d7202d8ac97584978a7bc
authorization=KakaoAK 3f4785dfe31d5b9d0d82fe7b68f315ed
settleId=d40d16f8-5cb0-4771-8ef4-cf97157181af

method=POST
name=rc
ci=YNLr2S4icA6JCxLmeDHPo6CTw3LGAEu2tTj/Unf9JFRj8z/rc+0o5R3iW6BnZLIWcssJY8bXE6Q1ki2s0MgxDg==
name=potato
ci=Dbf0Ecuod9YC0iNIPGXIPBP/JVr3a6nymx+MJHQBmUHgRwZ9up8YNgCdB6ms9Mxx7/U4U7e+mqplyDFMPXjkdg==
name=yg
ci=KvhdmEmq+EfoEPwXdj3WJpxmd5jNa7+0vo3pTBVhkHwVCuAah08T526woQKV19DcFjSXJwg8jpxiJyxTRzyb/g==
